// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmRopfNEH36rXjjhIbuuRgO48RtTqQgE',
    appId: '1:149377013217:web:107f983265316dcc3e2ea0',
    messagingSenderId: '149377013217',
    projectId: 'flutter-downloader-32254',
    authDomain: 'flutter-downloader-32254.firebaseapp.com',
    storageBucket: 'flutter-downloader-32254.appspot.com',
    measurementId: 'G-MZB17M1FFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWoMTzgM4Iod0WW0-ZpsLKrIPDKGOIFLU',
    appId: '1:149377013217:android:3026e19bea455cd73e2ea0',
    messagingSenderId: '149377013217',
    projectId: 'flutter-downloader-32254',
    storageBucket: 'flutter-downloader-32254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2ZnBMLf_eiakMWBDy6pU-Y7cz0N-EkA',
    appId: '1:149377013217:ios:c641b28629b0e29b3e2ea0',
    messagingSenderId: '149377013217',
    projectId: 'flutter-downloader-32254',
    storageBucket: 'flutter-downloader-32254.appspot.com',
    iosBundleId: 'com.example.videoDownloader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi2ZnBMLf_eiakMWBDy6pU-Y7cz0N-EkA',
    appId: '1:149377013217:ios:7e92e05c4cf1b0e43e2ea0',
    messagingSenderId: '149377013217',
    projectId: 'flutter-downloader-32254',
    storageBucket: 'flutter-downloader-32254.appspot.com',
    iosBundleId: 'com.example.videoDownloader.RunnerTests',
  );
}
